export const MICROSERVICES_CLIENTS = {
  AREAS_SERVICE: 'AREAS_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  GAMES_SERVICE: 'GAMES_SERVICE',
  NOTIFICATIONS_SERVICE: 'NOTIFICATIONS_SERVICE',
  USERS_SERVICE: 'USERS_SERVICE',
};
